export const productsList = () => [
  {
    id: 1,
    name: "L'Oreal Paris EverPure Aloe Blossom Deep Moisture Sheet Mask",
    category: "a care",
    image: process.env.PUBLIC_URL + "/images/products/d1.jpg",
    price: 10,
    brand: "Loreal",
  },
  {
    id: 2,
    name: "EverCreme Deep Nourish Conditioner",
    category: "hair care",
    image: process.env.PUBLIC_URL + "/images/products/d2.jpg",
    price: 9.98,
    brand: "Loreal",
  },
  {
    id: 3,
    name: "Palmers Natural Fusions Chia Seed & Argan Oil Hair Mask",
    category: "hair care",
    image: process.env.PUBLIC_URL + "/images/products/d3.jpg",
    price: 6.99,
    brand: "Palmers",
  },
  {
    id: 4,
    name: "L'Oreal Paris Serie Expert Vitamino Resveratrol Color Conditioner",
    category: "hair care",
    image: process.env.PUBLIC_URL + "/images/products/d4.jpg",
    price: 45.99,
    brand: "Loreal",
  },
  {
    id: 5,
    name: "Vitamin C Brightening Sheet Mask",
    category: "skin care",
    image: process.env.PUBLIC_URL + "/images/products/d5.jpg",
    price: 18.99,
    brand: "Vivo Per Lei",
  },
  {
    id: 6,
    name: "Garnier Hydrating Peel Off Beauty Face Mask",
    category: "skin care",
    image: process.env.PUBLIC_URL + "/images/products/d6.jpg",
    price: 3.29,
    brand: "Garnier",
  },

  {
    id: 8.99,
    name: "Zoya Remove Plus 3 in 1 Formula Polish Remover",
    category: "nails",
    image: process.env.PUBLIC_URL + "/images/products/d7.jpg",
    price: 13,
    brand: "Zoya",
  },
];
